# Generated by Django 5.2.17 on 2026-09-14 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('phone_number', models.CharField()),
                ('account_number', models.CharField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=256, null=True)),
                ('wallet', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_date', models.DateTimeField()),
                ('payout_amount', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='campuslife.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reference', models.CharField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='lodges/')),
                ('lodge_location', models.CharField(max_length=100)),
                ('lodge_price', models.CharField(blank=True, null=True)),
                ('agent_fee', models.CharField(blank=True, null=True)),
                ('agreement_fee', models.CharField(blank=True, null=True)),
                ('available_vacancy', models.IntegerField(default=0)),
                ('caretaker_number', models.CharField(blank=True, max_length=11, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('vacant_room', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_image', models.ImageField(upload_to='interiors/')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_images', to='campuslife.picture')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asked_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questioned_by', to=settings.AUTH_USER_MODEL)),
                ('downvote_question', models.ManyToManyField(blank=True, related_name='downvoted_question', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ManyToManyField(related_name='notification', to=settings.AUTH_USER_MODEL)),
                ('upvote_question', models.ManyToManyField(blank=True, related_name='upvoted_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_notification', to='campuslife.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to=settings.AUTH_USER_MODEL)),
                ('downvote_answer', models.ManyToManyField(blank=True, related_name='downvoted_answer', to=settings.AUTH_USER_MODEL)),
                ('parent_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_answers', to='campuslife.answer')),
                ('upvote_answer', models.ManyToManyField(blank=True, related_name='upvoted_answer', to=settings.AUTH_USER_MODEL)),
                ('question_replied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='campuslife.question')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_ratings', to='campuslife.picture')),
                ('rated_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('rated_by', 'picture_rating')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='campuslife.answer')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_replies', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_replies', to=settings.AUTH_USER_MODEL)),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_reviews', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campuslife.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(blank=True, null=True)),
                ('room_type', models.CharField(blank=True, null=True)),
                ('room_floor', models.CharField(blank=True, null=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='payment/')),
                ('room_video', models.FileField(blank=True, null=True, upload_to='payment/')),
                ('room_inspection', models.IntegerField(blank=True, null=True)),
                ('display', models.BooleanField(default=False)),
                ('uploaded', models.BooleanField(default=False)),
                ('vacancy_indicator', models.BooleanField(default=False)),
                ('caretaker_number', models.CharField(null=True)),
                ('agent', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agent_indicator', models.IntegerField(blank=True, null=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='campuslife.picture')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_agent', to='campuslife.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
