# Generated by Django 5.0.2 on 2024-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodge_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures/')),
                ('lodge_location', models.CharField(max_length=100)),
                ('lodge_price', models.IntegerField()),
                ('caretaker_number', models.IntegerField()),
            ],
        ),
    ]
