# Generated by Django 5.0.2 on 2024-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='available_vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
