# Generated by Django 5.0.2 on 2024-10-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslife', '0002_picture_available_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caretaker_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='lodge_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
