# Generated by Django 5.0.2 on 2024-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslife', '0003_alter_picture_caretaker_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caretaker_number',
            field=models.CharField(max_length=11),
        ),
    ]
