# Generated by Django 5.0.2 on 2024-11-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslife', '0004_alter_picture_caretaker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caretaker_number',
            field=models.CharField(default='09000000000', max_length=11),
        ),
    ]
