# Generated by Django 5.0.2 on 2024-11-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuslife', '0005_alter_picture_caretaker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caretaker_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
